package com.myspace.second;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class d1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public d1() {
    }




}